import type { Framework } from "./types.js";

export const FRAMEWORKS: Record<string, Framework> = {
  owasp: {
    name: "OWASP Top 10",
    version: "2021",
    description: "The 10 most critical web application security risks, used by 90% of security teams worldwide.",
    items: [
      { id: "A01", title: "Broken Access Control", description: "Are access controls enforced on all endpoints and functions? Are there privilege escalation paths or IDOR vulnerabilities?", risk: "CRITICAL" },
      { id: "A02", title: "Cryptographic Failures", description: "Is sensitive data encrypted in transit and at rest? Are weak or deprecated algorithms (MD5, SHA1, DES) in use?", risk: "CRITICAL" },
      { id: "A03", title: "Injection", description: "Is user input validated and sanitized? Are parameterized queries used for all database interactions?", risk: "CRITICAL" },
      { id: "A04", title: "Insecure Design", description: "Has the system been threat-modeled? Are secure design patterns and principles followed during development?", risk: "HIGH" },
      { id: "A05", title: "Security Misconfiguration", description: "Are default credentials changed? Are unnecessary features, ports, and services disabled? Are error messages exposing stack traces?", risk: "HIGH" },
      { id: "A06", title: "Vulnerable and Outdated Components", description: "Are all dependencies up to date? Is there a process for tracking CVEs in third-party libraries and frameworks?", risk: "HIGH" },
      { id: "A07", title: "Identification and Authentication Failures", description: "Is MFA enabled? Are session tokens properly managed? Are accounts locked after failed attempts?", risk: "HIGH" },
      { id: "A08", title: "Software and Data Integrity Failures", description: "Is the CI/CD pipeline secured against tampering? Are software updates and plugins verified before installation?", risk: "MEDIUM" },
      { id: "A09", title: "Security Logging and Monitoring Failures", description: "Are security events logged with sufficient detail? Is there alerting for suspicious activity and failed logins?", risk: "MEDIUM" },
      { id: "A10", title: "Server-Side Request Forgery (SSRF)", description: "Are outgoing requests from the server validated and allowlisted? Is access to internal resources restricted?", risk: "HIGH" },
    ],
  },
  nist: {
    name: "NIST SP 800-53",
    version: "Rev 5",
    description: "Federal security and privacy controls, required for US government systems and widely adopted in enterprise.",
    items: [
      { id: "AC-1",  title: "Access Control Policy",              description: "Is a formal access control policy documented, approved, and communicated to all personnel?",                                          risk: "HIGH" },
      { id: "AC-2",  title: "Account Management",                 description: "Are user accounts formally managed with defined roles? Are unused accounts disabled within 30 days?",                              risk: "HIGH" },
      { id: "AC-6",  title: "Least Privilege",                    description: "Are users and processes granted only the minimum permissions required to perform their functions?",                                 risk: "CRITICAL" },
      { id: "AU-2",  title: "Audit Events",                       description: "Are security-relevant events identified and logged consistently across all systems?",                                               risk: "HIGH" },
      { id: "AU-9",  title: "Protection of Audit Information",     description: "Are audit logs protected from unauthorized access, modification, or deletion?",                                                   risk: "MEDIUM" },
      { id: "CA-7",  title: "Continuous Monitoring",              description: "Is there a continuous monitoring strategy? Are security controls assessed on an ongoing basis?",                                   risk: "HIGH" },
      { id: "CM-6",  title: "Configuration Settings",             description: "Are security configuration settings documented and enforced for all systems and applications?",                                    risk: "MEDIUM" },
      { id: "IA-2",  title: "Identification and Authentication",   description: "Is multi-factor authentication required for all privileged accounts and remote access sessions?",                                risk: "CRITICAL" },
      { id: "IR-4",  title: "Incident Handling",                  description: "Is there a documented incident response plan? Has it been tested in the last 12 months?",                                        risk: "HIGH" },
      { id: "SC-8",  title: "Transmission Confidentiality",       description: "Is all data in transit encrypted using current standards (TLS 1.2+ or TLS 1.3)?",                                               risk: "HIGH" },
      { id: "SC-28", title: "Protection of Information at Rest",   description: "Is sensitive data encrypted at rest using AES-256 or equivalent?",                                                               risk: "HIGH" },
      { id: "SI-3",  title: "Malicious Code Protection",          description: "Is anti-malware deployed and updated on all endpoints? Are scheduled scans configured?",                                         risk: "HIGH" },
      { id: "SI-10", title: "Information Input Validation",        description: "Is all input validated for type, length, format, and range before processing?",                                                  risk: "MEDIUM" },
    ],
  },
  iso27001: {
    name: "ISO 27001",
    version: "2022",
    description: "International standard for information security management systems (ISMS), required for ISO certification.",
    items: [
      { id: "A.5.1",  title: "Policies for Information Security",   description: "Are information security policies defined, approved by management, and communicated to all staff?",                             risk: "HIGH" },
      { id: "A.5.15", title: "Access Control",                      description: "Are rules for access control defined and implemented based on business and information security requirements?",               risk: "CRITICAL" },
      { id: "A.6.1",  title: "Screening",                           description: "Are background verification checks conducted on all employees and contractors prior to onboarding?",                          risk: "HIGH" },
      { id: "A.7.9",  title: "Security of Assets Off-Premises",     description: "Are assets used outside organizational premises protected with controls accounting for the increased risk?",                risk: "MEDIUM" },
      { id: "A.8.2",  title: "Privileged Access Rights",            description: "Are privileged access rights restricted, reviewed regularly, and granted on a need-to-use basis only?",                     risk: "CRITICAL" },
      { id: "A.8.5",  title: "Secure Authentication",               description: "Are secure authentication procedures implemented, including MFA for all sensitive and privileged systems?",                 risk: "CRITICAL" },
      { id: "A.8.7",  title: "Protection Against Malware",          description: "Are controls against malware implemented and supported by regular user awareness training?",                                 risk: "HIGH" },
      { id: "A.8.13", title: "Information Backup",                  description: "Are backup copies of information maintained, tested regularly for recoverability, and stored securely off-site?",             risk: "HIGH" },
      { id: "A.8.16", title: "Monitoring Activities",               description: "Are networks, systems, and applications monitored for anomalous behaviour and potential security incidents?",                 risk: "HIGH" },
      { id: "A.8.24", title: "Use of Cryptography",                 description: "Is cryptography used appropriately and consistently to protect confidentiality and integrity of information?",                risk: "HIGH" },
      { id: "A.8.28", title: "Secure Coding",                       description: "Are secure coding principles applied across all development? Is security testing performed at every stage?",               risk: "MEDIUM" },
      { id: "A.8.32", title: "Change Management",                   description: "Are changes to information processing facilities and systems managed via a formal change management procedure?",           risk: "MEDIUM" },
    ],
  },
  pcidss: {
    name: "PCI-DSS",
    version: "v4.0",
    description: "Payment Card Industry Data Security Standard for organizations that handle branded credit cards.",
    items: [
      { id: "Req-1", title: "Install and Maintain Network Security Controls", description: "Are network security controls (NSCs) installed, maintained, and configured to protect the cardholder data environment?", risk: "CRITICAL" },
      { id: "Req-2", title: "Apply Secure Configurations to All System Components", description: "Are system components configured securely, and are vendor defaults changed?", risk: "HIGH" },
      { id: "Req-3", title: "Protect Stored Account Data", description: "Is stored cardholder data protected and encrypted where necessary?", risk: "CRITICAL" },
      { id: "Req-4", title: "Protect Cryptography During Transmission", description: "Is cardholder data encrypted with strong cryptography during transmission over open, public networks?", risk: "CRITICAL" },
      { id: "Req-5", title: "Protect Systems from Malicious Software", description: "Are anti-malware solutions deployed and regularly updated on all commonly affected systems?", risk: "HIGH" },
      { id: "Req-6", title: "Develop and Maintain Secure Systems", description: "Are security vulnerabilities identified and addressed? Are systems and software developed securely?", risk: "HIGH" },
      { id: "Req-7", title: "Restrict Access to System Components", description: "Is access to system components and cardholder data restricted by business need to know?", risk: "CRITICAL" },
      { id: "Req-8", title: "Identify Users and Authenticate Access", description: "Are unique IDs assigned and multi-factor authentication (MFA) used to verify user identities?", risk: "CRITICAL" },
      { id: "Req-9", title: "Restrict Physical Access", description: "Is physical access to the cardholder data environment strictly restricted and monitored?", risk: "HIGH" },
      { id: "Req-10", title: "Log and Monitor All Access", description: "Is all access to system components and cardholder data logged and monitored?", risk: "HIGH" },
      { id: "Req-11", title: "Test Security of Systems Regularly", description: "Are systems and networks tested regularly (e.g., vulnerability scans, penetration testing)?", risk: "HIGH" },
      { id: "Req-12", title: "Support Information Security", description: "Is there a documented and maintained policy that addresses information security for all personnel?", risk: "MEDIUM" }
    ],
  },
  soc2: {
    name: "SOC 2 Type II",
    version: "2017 Trust Services Criteria",
    description: "Security framework based on the Trust Services Criteria (TSC) for managing customer data.",
    items: [
      { id: "CC1", title: "Control Environment", description: "Does the organization demonstrate a commitment to integrity and ethical values?", risk: "MEDIUM" },
      { id: "CC2", title: "Communication and Information", description: "Does the organization generate and use relevant, quality information to support internal control?", risk: "MEDIUM" },
      { id: "CC3", title: "Risk Assessment", description: "Does the organization perform regular risk assessments to identify and mitigate risks to its objectives?", risk: "HIGH" },
      { id: "CC4", title: "Monitoring Activities", description: "Are ongoing evaluations conducted to ascertain whether the components of internal control are present and functioning?", risk: "HIGH" },
      { id: "CC5", title: "Control Activities", description: "Does the organization select and develop control activities that mitigate risks to acceptable levels?", risk: "HIGH" },
      { id: "CC6", title: "Logical and Physical Access", description: "Are logical and physical access controls in place to restrict access to systems and data to authorized personnel only?", risk: "CRITICAL" },
      { id: "CC7", title: "System Operations", description: "Are system operations monitored, and are deviations from expected performance detected and addressed?", risk: "HIGH" },
      { id: "CC8", title: "Change Management", description: "Are changes to systems, applications, and infrastructure authorized, tested, and approved before implementation?", risk: "HIGH" },
      { id: "CC9", title: "Risk Mitigation", description: "Are activities implemented to manage and mitigate risks associated with business disruptions?", risk: "HIGH" }
    ],
  },
  hipaa: {
    name: "HIPAA Security Rule",
    version: "Current",
    description: "National standards to protect individuals' electronic personal health information (ePHI).",
    items: [
      { id: "164.308(a)(1)", title: "Security Management Process", description: "Are policies and procedures implemented to prevent, detect, contain, and correct security violations?", risk: "HIGH" },
      { id: "164.308(a)(3)", title: "Workforce Security", description: "Are there procedures to ensure appropriate access to ePHI for workforce members and to prevent unauthorized access?", risk: "HIGH" },
      { id: "164.308(a)(4)", title: "Information Access Management", description: "Are policies implemented for authorizing access to ePHI based on the user's role?", risk: "CRITICAL" },
      { id: "164.308(a)(5)", title: "Security Awareness and Training", description: "Is a security awareness and training program implemented for all members of the workforce?", risk: "MEDIUM" },
      { id: "164.308(a)(7)", title: "Contingency Plan", description: "Are policies established for responding to emergencies or system failures that damage systems containing ePHI?", risk: "HIGH" },
      { id: "164.310(a)(1)", title: "Facility Access Controls", description: "Are physical access controls in place to limit access to facilities where ePHI is housed?", risk: "HIGH" },
      { id: "164.312(a)(1)", title: "Access Control", description: "Are technical policies implemented to allow access only to authorized persons or software programs?", risk: "CRITICAL" },
      { id: "164.312(b)", title: "Audit Controls", description: "Are hardware, software, or procedural mechanisms in place to record and examine access and other activity in information systems?", risk: "HIGH" },
      { id: "164.312(e)(1)", title: "Transmission Security", description: "Are technical security measures in place to guard against unauthorized access to ePHI transmitted over electronic communications networks?", risk: "CRITICAL" }
    ],
  },
  cisv8: {
    name: "CIS Controls",
    version: "v8",
    description: "Prioritized set of actions that collectively form a defense-in-depth set of best practices that mitigate the most common attacks against systems and networks.",
    items: [
      { id: "CIS-1", title: "Inventory and Control of Enterprise Assets", description: "Are all enterprise assets actively managed (inventoried, tracked, and corrected)?", risk: "HIGH" },
      { id: "CIS-2", title: "Inventory and Control of Software Assets", description: "Is all software actively managed to ensure only authorized software is installed and executed?", risk: "HIGH" },
      { id: "CIS-3", title: "Data Protection", description: "Are processes and technical controls developed to identify, classify, securely handle, retain, and dispose of data?", risk: "CRITICAL" },
      { id: "CIS-4", title: "Secure Configuration of Enterprise Assets", description: "Are secure configurations established and maintained for enterprise assets and software?", risk: "HIGH" },
      { id: "CIS-5", title: "Account Management", description: "Are processes and tools in place to assign and manage authorization to credentials for user accounts?", risk: "HIGH" },
      { id: "CIS-6", title: "Access Control Management", description: "Are processes and tools used to create, assign, manage, and revoke access credentials?", risk: "CRITICAL" },
      { id: "CIS-7", title: "Continuous Vulnerability Management", description: "Is a plan implemented to continuously assess and track vulnerabilities on all enterprise assets?", risk: "HIGH" },
      { id: "CIS-8", title: "Audit Log Management", description: "Are processes and tools used to collect, review, and retain audit logs for security events?", risk: "HIGH" },
      { id: "CIS-9", title: "Email and Web Browser Protections", description: "Are protections improved and maintained for email and web vectors?", risk: "MEDIUM" },
      { id: "CIS-10", title: "Malware Defenses", description: "Is the installation, spread, and execution of malicious applications prevented or controlled?", risk: "HIGH" }
    ],
  },
  gdpr: {
    name: "GDPR",
    version: "2016/679",
    description: "General Data Protection Regulation covering data protection and privacy in the EU.",
    items: [
      { id: "Art-5", title: "Principles relating to processing of personal data", description: "Is personal data processed lawfully, fairly, transparently, and securely, limited to what is necessary?", risk: "CRITICAL" },
      { id: "Art-15", title: "Right of access by the data subject", description: "Are processes in place to allow data subjects to access their personal data and understand how it is processed?", risk: "HIGH" },
      { id: "Art-17", title: "Right to erasure ('right to be forgotten')", description: "Are mechanisms implemented to delete personal data without undue delay when requested by the data subject?", risk: "HIGH" },
      { id: "Art-25", title: "Data protection by design and by default", description: "Are technical and organizational measures implemented to ensure that data protection principles are integrated into processing activities?", risk: "HIGH" },
      { id: "Art-32", title: "Security of processing", description: "Are appropriate technical and organizational measures implemented to ensure a level of security appropriate to the risk, including encryption?", risk: "CRITICAL" },
      { id: "Art-33", title: "Notification of a personal data breach", description: "Is there a documented process to notify the supervisory authority of a personal data breach within 72 hours?", risk: "HIGH" },
      { id: "Art-35", title: "Data protection impact assessment", description: "Are DPIAs conducted for processing operations likely to result in a high risk to the rights and freedoms of natural persons?", risk: "MEDIUM" }
    ],
  }
};
